name: CI

on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
      - uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
        with:
          swift-version: "5.5"
      - uses: actions/checkout@v2
      - name: Build tools
        run: make build-tools
      - name: Run lint
        run: make lint-strict

  build:
    name: Build (${{ matrix.os }}, Swift ${{ matrix.swift-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift-version: ["5.5"]
    steps:
      - uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
        with:
          swift-version: ${{ matrix.swift-version }}
      - uses: actions/checkout@v2
      - name: Build
        run: make build

  test:
    name: Test (${{ matrix.os }}, Swift ${{ matrix.swift-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift-version: ["5.5"]
    steps:
      - uses: fwal/setup-swift@2040b795e5c453c3a05fcb8316496afc8a74f192
        with:
          swift-version: ${{ matrix.swift-version }}
      - uses: actions/checkout@v2
      - name: Test
        run: make test
